name: Greetings
# https://github.com/marketplace/actions/first-interaction

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
      with:
        repo_token: ${{ github.token }}
        issue_message: 'Ahoy!'
        pr_message: 'Ahoy!'
